# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: <i class="fa-solid fa-house"></i> HOME
    url: /
    weight: 10
  - name: <i class="fa-solid fa-user"></i> ABOUT
    url: 'about'
    weight: 20
  - name: <span id="research-menu-label"><i class="fa-solid fa-flask"></i> RESEARCH</span>
    identifier: research
    url: '/#projects'
    weight: 30
  - name: <i class="fa-solid fa-shapes"></i> Statistics in Metric Spaces
    parent: research
    url: 'project/metric-spaces'
    weight: 10
  - name: <i class="fa-solid fa-bacteria"></i> Microbiome Data Analysis
    parent: research
    url: 'project/microbiome'
    weight: 11
  - name: <i class="fa-solid fa-brain"></i> Brain-Computer Interfaces
    parent: research
    url: 'project/bci'
    weight: 12
  - name: <i class="fa-solid fa-share-nodes"></i> Network Analysis
    parent: research
    url: 'project/network'
    weight: 13
  - name: <i class="fa-solid fa-chart-column"></i> Statistical Methodology
    parent: research
    url: 'project/misc'
    weight: 14
  - name: <i class="fa-solid fa-gears"></i> Applied Research
    parent: research
    url: 'project/applied'
    weight: 15
  - name: Publications
    parent: research
    url: 'publication'
    weight: 20
  - name: Talks
    parent: research
    url: 'event'
    weight: 30
  - name: Software
    parent: research
    url: 'software'
    weight: 40
  - name: <i class="fa-solid fa-chalkboard-user"></i> TEACHING
    url: 'teaching'
    weight: 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
